[workspace]
members = ["bevy_rapier2d", "bevy_rapier3d", "bevy_rapier_benches3d", "ci"]
resolver = "2"

[workspace.dependencies]
rapier2d = "0.35.0-beta.0"
rapier3d = "0.35.0-beta.0"

[profile.dev]
# Use slightly better optimization by default, as examples otherwise seem laggy.
opt-level = 1

[profile.release]
codegen-units = 1

[patch.crates-io]
#rapier2d = { path = "../rapier/crates/rapier2d" }
#rapier3d = { path = "../rapier/crates/rapier3d" }
bevy = { git = "https://github.com/bevyengine/bevy", rev = "87a24bf95af15ed707fe634969994852155a2eac" }
